### ISSUE TITLE
Can't login to seedbox

### ISSUE THREAD

**Issue by erigmac** [CCExtractor/rutorrent-flutter#143]
I have installed the app into iOS however I was not able to log in to Whatbox.
Is there any solution?

**Comment by cfsmp3** [comment]
> I have installed the app into iOS however I was not able to log in to Whatbox.
> Is there any solution?

This is a question for whatbox. No way our team is going to do the job of seedbox providers :-) If it doesn't work with whatbox ask them to give it a try and send a pull request to fix it :-)

Only exception is Xirvik and just because that's we're using to develop and test (and still if a Xirvik customer comes asking for help we'd say the same thing - however we know it works well with those seedboxes).

Sorry.
