### ISSUE TITLE
package deprecated: BottomNavigationBar

### ISSUE THREAD

**Issue by santhoshivan23** [CCExtractor/rutorrent-flutter#21]
_title_ field of BottomNavigationBar is deprecated. Use _label_ instead.

**Comment by saiankit** [comment]
I can fix this up. Can you assign the issue to me ?

**Comment by saiankit** [comment]
@santhoshivan23 
I don't think _title_ has to be replaced with _label_ even if it has been deprecated because the Bottom Navigation Bar's title is styled to be in **Bold** which can't be made possible if label is used. 
But if the **Bold** is not an important UI Criterion then the title can be replaced with label which improves the accessibility experience ( https://flutter.dev/docs/release/breaking-changes/bottom-navigation-title-to-label )
@harchani-ritik  Can you please give your thoughts on this ?

**Comment by santhoshivan23** [comment]
@saiankit I agree! We can make a custom bottom navigation bar if bold text is a matter of concern.

**Comment by harchani-ritik** [comment]
Yes, guys, sorry for the delay, anyone who wishes can work on this.
